### ISSUE TITLE
categorize resources to relevant topic

### ISSUE THREAD

**Issue by myugan** [walidshaari/Certified-Kubernetes-Security-Specialist#26]
we need to categorize any resources with create a new directory maybe something like this `container-security` or `challenges` if there is some exercises to practicing (hands-on) and also other stuff, what do you think? because some resources maybe will related to container stuff not kubernetes itself (cluster)

**Comment by walidshaari** [comment]
sure, why not? CKS does cover container security, would you like to have a folder that has generic containers and kubernetes security resources? something like below?
```
[walid@honk Certified-Kubernetes-Security-Specialist]$ tree .
.
├── generic-kubernetes-containers-security
│   ├── challenges.md
│   ├── Containers.md
│   ├── k8d.md
│   ├── README.dmd
│   └── README.md
├── hands-on
│   └── 00-kind-cluster
│       ├── kind-1m3w-nocni.yaml
│       ├── kind-create-cluster.asc
│       └── README.md
├── kubernetes-security-specialist-logo-300x285.png
├── license.txt
└── README.md
```

**Comment by myugan** [comment]
LGTM @walidshaari let's do it for upcoming repo updates

**Comment by walidshaari** [comment]
so you just the new directory and its layout

```
├── generic-kubernetes-containers-security
│   ├── Challenges.md
│   ├── Containers.md
│   ├── Kubernetes.md
│   └── README.md
```
