### ISSUE TITLE
ToDo list: site enhacments request via social network interactions

### ISSUE THREAD

**Issue by walidshaari** [walidshaari/Certified-Kubernetes-Security-Specialist#31]
some of the requests that came via Linkedin/Twitter
- Use GitHub pages
- Explain the why behind controls

**Comment by myugan** [comment]
Sounds good to use GitHub pages and it will looks nice to share our resources to other.

**Comment by myugan** [comment]
I've recommendation to use something like this https://squidfunk.github.io/mkdocs-material/, what do you think @walidshaari? or any themes looks like fit to share our references.

**Comment by walidshaari** [comment]
Interesting indeed, need to take a closer look
