### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Tej-Singh-Rana** [walidshaari/Certified-Kubernetes-Security-Specialist#56]
In Monitoring, logging and runtime security section -
Under the topic **Falco Kubernetes manifests** - https://github.com/falcosecurity/evolution/tree/master/deploy/kubernetes/kernel-and-k8s-audit
This link is not working. 

Thanks,

**Comment by myugan** [comment]
Thanks for letting us know, we will update it soon @Tej-Singh-Rana
