### ISSUE TITLE
Pod Security policy removed from k8s v1.25

### ISSUE THREAD

**Issue by HamzaM1** [walidshaari/Certified-Kubernetes-Security-Specialist#70]
Since the pod security policy has been removed from 1.25, are we going to be asked any questions on it?
Would the questions instead be based on pod security admission?

**Comment by walidshaari** [comment]
PodSecurityPolicy is deprecated in v1.21+ and will be unavailable in
v1.25 onwards, as the current exam is based on 1.25 and soon 1.26, most likely you are right https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/ will be the replacement is my guess. have not done any research on the subject, just my quick opinion

**Comment by HamzaM1** [comment]
I have taken the CKS exam recently.
Without breaking the NDA, I can say that you absolutely need to know pod security admission and not pod security policy because the lab environment is now running on v1.25

**Comment by walidshaari** [comment]
Thank you, @HamzaM1 that is precisely why we merged pull request #68 
thank you once again for your time and sharing your concerns for other exam takers,  keep learning and keep being awesome

**Comment by HamzaM1** [comment]
No problem at all. I look up to you a lot Mr. Shaari. Your online content has greatly benefited me. I hope to reach your level one day. I will close this issue.
